### ISSUE TITLE
Can we use gen-env in NestJS ?

### ISSUE THREAD

**Issue by charleskan** [beenotung/gen-env#2]
![image](https://user-images.githubusercontent.com/71898304/187682804-6dab0bcb-aa95-409d-b645-cce2695b3fec.png)

After I ran gen-env, it showed 'done' but I can't find the '.env' .  

Does it means we can't use gen-env in NestJS?

**Comment by beenotung** [comment]
You can use gen-env in any javascript / typescript project. It scans for usage on process.env or env.

E.g. `process.env.PORT` or `let { PORT } = env`

If you have not used any environment variable yet, it will not be able to collect list of env var.

**Comment by charleskan** [comment]
thx! i got it
